2021-02-26 14:10:27.480 295010 DEBUG neutron.agent.linux.utils [-] Running command: ['sudo', 'neutron-rootwrap', '/etc/neutron/rootwrap.conf', 'ip', 'netns', 'exec', 'qrouter-06ff8bac-d832-4cf4-bae8-4ae2297fe062', 'sysctl', '-w', 'net.ipv4.ip_forward=1'] create_process /usr/lib/python3/dist-packages/neutron/agent/linux/utils.py:87
2021-02-26 14:10:28.086 295010 DEBUG neutron.agent.linux.utils [-] Running command: ['sudo', 'neutron-rootwrap', '/etc/neutron/rootwrap.conf', 'ip', 'netns', 'exec', 'qrouter-06ff8bac-d832-4cf4-bae8-4ae2297fe062', 'sysctl', '-w', 'net.ipv4.conf.all.arp_ignore=1'] create_process /usr/lib/python3/dist-packages/neutron/agent/linux/utils.py:87
2021-02-26 14:10:28.455 295010 DEBUG neutron.agent.linux.utils [-] Running command: ['sudo', 'neutron-rootwrap', '/etc/neutron/rootwrap.conf', 'ip', 'netns', 'exec', 'qrouter-06ff8bac-d832-4cf4-bae8-4ae2297fe062', 'sysctl', '-w', 'net.ipv4.conf.all.arp_announce=2'] create_process /usr/lib/python3/dist-packages/neutron/agent/linux/utils.py:87
2021-02-26 14:10:28.897 295010 DEBUG neutron.agent.linux.utils [-] Running command: ['sudo', 'neutron-rootwrap', '/etc/neutron/rootwrap.conf', 'ip', 'netns', 'exec', 'qrouter-06ff8bac-d832-4cf4-bae8-4ae2297fe062', 'sysctl', '-w', 'net.ipv6.conf.all.forwarding=1'] create_process /usr/lib/python3/dist-packages/neutron/agent/linux/utils.py:87
2021-02-26 14:10:29.218 295010 DEBUG oslo_concurrency.lockutils [-] Lock "resize_greenpool" acquired by "neutron.agent.l3.agent.L3NATAgent._resize_process_pool" :: waited 0.000s inner /usr/lib/python3/dist-packages/oslo_concurrency/lockutils.py:355
2021-02-26 14:10:29.219 295010 DEBUG oslo_concurrency.lockutils [-] Lock "resize_greenpool" released by "neutron.agent.l3.agent.L3NATAgent._resize_process_pool" :: held 0.001s inner /usr/lib/python3/dist-packages/oslo_concurrency/lockutils.py:367
2021-02-26 14:10:29.703 295038 DEBUG neutron.privileged.agent.linux.ip_lib [-] Interface rfp-06ff8bac-d not found in namespace qrouter-06ff8bac-d832-4cf4-bae8-4ae2297fe062 get_link_id /usr/lib/python3/dist-packages/neutron/privileged/agent/linux/ip_lib.py:253
2021-02-26 14:10:29.703 295038 DEBUG oslo.privsep.daemon [-] privsep: reply[140247114965216]: (4, False) _call_back /usr/lib/python3/dist-packages/oslo_privsep/daemon.py:510
2021-02-26 14:10:29.705 295010 DEBUG neutron.agent.l3.router_info [-] Process updates, router 06ff8bac-d832-4cf4-bae8-4ae2297fe062 process /usr/lib/python3/dist-packages/neutron/agent/l3/router_info.py:1237
2021-02-26 14:10:29.705 295010 DEBUG neutron.agent.l3.router_info [-] adding internal network: prefix(qr-), port(43423ab0-0173-45d9-aaf7-35fde5822531) _internal_network_added /usr/lib/python3/dist-packages/neutron/agent/l3/router_info.py:495
2021-02-26 14:10:29.727 295038 DEBUG oslo.privsep.daemon [-] privsep: reply[140247114965216]: (4, True) _call_back /usr/lib/python3/dist-packages/oslo_privsep/daemon.py:510
2021-02-26 14:10:29.729 295010 INFO neutron.agent.linux.interface [-] Device qr-43423ab0-01 already exists
2021-02-26 14:10:29.764 295038 DEBUG oslo.privsep.daemon [-] privsep: reply[140247114965216]: (4, ({'header': {'length': 36, 'type': 2, 'flags': 256, 'sequence_number': 255, 'pid': 295084, 'error': None, 'target': 'qrouter-06ff8bac-d832-4cf4-bae8-4ae2297fe062', 'stats': Stats(qsize=0, delta=0, delay=0)}, 'event': 'NLMSG_ERROR'},)) _call_back /usr/lib/python3/dist-packages/oslo_privsep/daemon.py:510
2021-02-26 14:10:29.765 295010 DEBUG neutron.agent.linux.interface [-] init_router_port: device_name(qr-43423ab0-01), namespace(qrouter-06ff8bac-d832-4cf4-bae8-4ae2297fe062) init_router_port /usr/lib/python3/dist-packages/neutron/agent/linux/interface.py:169
2021-02-26 14:10:29.794 295038 DEBUG oslo.privsep.daemon [-] privsep: reply[140247114965216]: (4, {'mtu': 1500, 'qlen': 1000, 'state': 'UNKNOWN', 'qdisc': 'noqueue', 'brd': 'ff:ff:ff:ff:ff:ff', 'link/ether': 'fa:16:3e:20:84:64', 'alias': None, 'allmulticast': False, 'link_kind': 'openvswitch'}) _call_back /usr/lib/python3/dist-packages/oslo_privsep/daemon.py:510

