192.168.100.39 - - [04/May/2021:01:39:46 +0000] "GET / HTTP/1.1" 300 564 "-" "openstacksdk/0.50.0 keystoneauth1/4.2.1 python-requests/2.23.0 CPython/3.6.9"
[Tue May 04 01:39:46.541666 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers [req-f49513e0-f977-47f3-a776-88b148b0584f 88fd1758ba18459fb240783f086df248 e178e8f4d8764
[Tue May 04 01:39:46.541698 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers Traceback (most recent call last):
[Tue May 04 01:39:46.541705 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers   File "/usr/lib/python3/dist-packages/barbican/api/controllers/__init__.py", line 101, 
[Tue May 04 01:39:46.541712 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers     return fn(inst, *args, **kwargs)
[Tue May 04 01:39:46.541718 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers   File "/usr/lib/python3/dist-packages/barbican/api/controllers/__init__.py", line 87, i
[Tue May 04 01:39:46.541735 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers     return fn(inst, *args, **kwargs)
[Tue May 04 01:39:46.541741 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers   File "/usr/lib/python3/dist-packages/barbican/api/controllers/secrets.py", line 207, i
[Tue May 04 01:39:46.541747 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers     resp = self._on_get_secret_payload(self.secret,
[Tue May 04 01:39:46.541753 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers   File "/usr/lib/python3/dist-packages/barbican/api/controllers/secrets.py", line 183, i
[Tue May 04 01:39:46.541759 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers     return plugin.get_secret(accept_header,
[Tue May 04 01:39:46.541765 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers   File "/usr/lib/python3/dist-packages/barbican/plugin/resources.py", line 146, in get_s
[Tue May 04 01:39:46.541771 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers     return tr.denormalize_after_decryption(secret_dto.secret,
[Tue May 04 01:39:46.541777 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers   File "/usr/lib/python3/dist-packages/barbican/plugin/util/translations.py", line 112, 
[Tue May 04 01:39:46.541782 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers     unencrypted = base64.decode_as_bytes(unencrypted)
[Tue May 04 01:39:46.541788 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers   File "/usr/lib/python3/dist-packages/oslo_serialization/base64.py", line 70, in decode
[Tue May 04 01:39:46.541794 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers     encoded = encoded.decode('ascii')
[Tue May 04 01:39:46.541800 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in r
[Tue May 04 01:39:46.541806 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.541 21282 ERROR barbican.api.controllers \x1b[00m
[Tue May 04 01:39:46.542964 2021] [wsgi:error] [pid 21282:tid 139806546745088] [remote 192.168.100.39:52938] 2021-05-04 01:39:46.542 21282 INFO barbican.api.middleware.context [req-f49513e0-f977-47f3-a776-88b148b0584f 88fd1758ba18459fb240783f086df248 e178e8f
192.168.100.39 - - [04/May/2021:01:39:46 +0000] "GET /v1/secrets/c6ab8a46-0f96-4861-942b-5a34642767fe/payload HTTP/1.1" 500 385 "-" "openstacksdk/0.50.0 keystoneauth1/4.2.1 python-requests/2.23.0 CPython/3.6.9"

